<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Document numbers (bill_number, invoice_no, receipt_no, voucher_no) were
     * globally unique across all tenants, but generated by counting only the
     * current company's records — so once any company used e.g. "PB-2026-00001",
     * no other company could ever use it again, causing a 1062 duplicate-entry
     * error on what looks like a brand new bill. Scopes uniqueness to
     * (company_id, number) instead.
     */
    public function up(): void
    {
        Schema::table('purchase_bills', function (Blueprint $table) {
            $table->dropUnique('purchase_bills_bill_number_unique');
            $table->unique(['company_id', 'bill_number']);
        });

        Schema::table('sales_orders', function (Blueprint $table) {
            $table->dropUnique('sales_orders_invoice_no_unique');
            $table->unique(['company_id', 'invoice_no']);
        });

        Schema::table('payment_ins', function (Blueprint $table) {
            $table->dropUnique('payment_ins_receipt_no_unique');
            $table->unique(['company_id', 'receipt_no']);
        });

        Schema::table('supplier_payments', function (Blueprint $table) {
            $table->dropUnique('supplier_payments_voucher_no_unique');
            $table->unique(['company_id', 'voucher_no']);
        });
    }

    public function down(): void
    {
        Schema::table('purchase_bills', function (Blueprint $table) {
            $table->dropUnique(['company_id', 'bill_number']);
            $table->unique('bill_number');
        });

        Schema::table('sales_orders', function (Blueprint $table) {
            $table->dropUnique(['company_id', 'invoice_no']);
            $table->unique('invoice_no');
        });

        Schema::table('payment_ins', function (Blueprint $table) {
            $table->dropUnique(['company_id', 'receipt_no']);
            $table->unique('receipt_no');
        });

        Schema::table('supplier_payments', function (Blueprint $table) {
            $table->dropUnique(['company_id', 'voucher_no']);
            $table->unique('voucher_no');
        });
    }
};
